# Generated by Django 3.2.4 on 2021-06-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('message', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
    ]
