# Generated by Django 3.2.4 on 2021-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210618_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Name')),
                ('author', models.CharField(max_length=240, verbose_name='Name')),
                ('description', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
    ]
