# Generated by Django 3.2.4 on 2021-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_messages_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('username', models.CharField(max_length=240, verbose_name='username')),
                ('password', models.CharField(max_length=240, verbose_name='password')),
            ],
        ),
    ]
