# Generated by Django 3.2.4 on 2021-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pictur_url',
            field=models.CharField(default='', max_length=240, verbose_name='pictur'),
            preserve_default=False,
        ),
    ]
