# Generated by Django 3.2.4 on 2021-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_books_pictur_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_released',
            field=models.CharField(default=1, max_length=240, verbose_name='date_released'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(default=-1, max_length=240, verbose_name='isbn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='subtitle',
            field=models.CharField(default=-1.0, max_length=240, verbose_name='subtitle'),
            preserve_default=False,
        ),
    ]
